@startuml

participant Worker
participant Master

Worker -> Master: Registration Request
note left
    ip:
    port:
end note
Master -> Worker: Registration Result
note right
    type: "REGISTER_RESULT"
    worker number:
    message: "You are the ""th worker"
end note

== Main Sorting Workflow ==

Worker -> Master: Sampling Request
note left
    sampling data
end note
Master -> Worker: Sampling Result
note right
    quantiles
end note
Worker -> Worker : Local Sorting & Partitioning

Worker -> Worker : Shuffling
note left
    data exchange between workers
end note
Worker -> Worker : Local Sorting
Worker -> Master: Sorting End Notification
note left
    worker number
end note
alt all workers notified
    Master -> Worker: Job Completion Acknowledgment
else waiting for other workers
    Master -> Worker: Wait for Other Workers
end alt

@enduml
