syntax = "proto3";

package shuffle.control;

message RoundStart {
    int32 round = 1;
}

message RoundDone {
    int32 round = 1;
    int32 worker_id = 2;
}

/* 새로 추가: Worker가 Master에 접속할 때 쓰는 등록 메시지 */
message Register {
  int32 worker_id = 1;
  string ip       = 2; // 필요 없으면 지워도 됨
  int32 port      = 3; // 필요 없으면 지워도 됨
}

message ShuffleMsg {
    oneof payload {
        RoundStart start = 1;
        RoundDone done = 2;
    }
}

service ShuffleControlService {
    rpc GrpcShuffleStreamControl(stream ShuffleMsg) returns (stream ShuffleMsg);
}
