@startuml

package Master {
    object MainMaster {
        WorkerInfos workerInfos
    }

    folder "Managers" {
        class ShuffleManager {
            + executeRounds(allRounds)
            + executeRound(roundId)
        }
    }

    folder "Services" {
        class ShuffleWorkerService {
            + broadcastNextRound(newRound: Int)
            + broadcastDeadWorker(workerId: Int)

            - onWorkerRoundDone(workerId: Int)
            - onWorkerDead(workerId: Int)

            - onWorkerRegister(workerId: Int, ip: String, port: Int)
            - onHeartbeat(workerId: Int)
            + start()
        }
    }
    
    folder "Repositories" {
        class GrpcShuffleRepository {
            Map<Int, StreamObserver> streamObservers

            + sendNextRound(workerId: Int, round: Int)
            + sendDeadWorker(workerId: Int, round: Int = 0)
            + onWorkerRoundDoneHandler(handler)
            + onWorkerDeadHandler(handler)

            - openServer()
            - close()

            + onRegisterHandler(handler)
            + onHeartbeatHandler(handler)
            + onStreamOpenedHandler(handler)
        }
    }
    
    folder Model {
        object GrpcShuffleStream <<Proto>>

        class NextRound <<ProtoMsg>>
        class DeadWorker <<ProtoMsg>>
        class Register  <<ProtoMsg>>
        class RoundDone <<ProtoMsg>>
        class Heartbeat <<ProtoMsg>>
    }

    ' Relationships
    MainMaster --> Managers
    Managers --> Services
    Services --> Repositories
    Repositories --> Model

    GrpcShuffleRepository ..> ShuffleWorkerService : onRegisterHandler()\n onHeartbeatHandler()\n onWorkerRoundDoneHandler()
    ShuffleWorkerService ..> GrpcShuffleRepository : sendNextRound()/sendDeadWorker()


}


@enduml